type Query {
    summary: SummaryResponse
}

type SummaryResponse {
    stageSummary(stageId: Int, workUnitStatusList: [WorkUnitStatus!]): StageSummary
    clientSummary(clientId: String, workUnitStatusList: [WorkUnitStatus!]): ClientSummary
}

type StageSummary {
    workUnitCount: Int!
    stageId: Int!
    workUnitStatusList: [WorkUnitStatus!]!
}

type ClientSummary {
    workUnitCount: Int!
    clientId: String!
    workUnitStatusList: [WorkUnitStatus!]!
}

enum WorkUnitStatus {
    NEW
    ASSIGNED
    COMPLETE
    CANCELLED
}
