spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://192.168.1.224:3306/ramsey?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}

ramsey:
  startup:
    initialize-test-data:
      enabled: false