spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://172.16.0.222:3306/ramsey-test?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true
    username: ${DB_USER}
    password: ${DB_PASS}