spring:
  jpa:
    hibernate:
      ddl-auto: create  # Creates tables
    defer-datasource-initialization: true
  sql:
    init:
      mode: always  # Runs data.sql for inserts
  datasource:
    url: jdbc:mysql://192.168.1.224:3306/ramsey-dev?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}

ramsey:
  startup:
    initialize-test-data:
      enabled: false # Pulls data at startup from production AP

server:
  tomcat:
#    remote-ip-header: x-forwarded-for
#    protocol-header: x-forwarded-proto
    redirect-context-root: false
  forward-headers-strategy: framework

springdoc:
  api-docs:
    enabled: off
    path: /api-docs/json
  swagger-ui:
    path: /api-docs/ # <==== mind the trailing slash
    disable-swagger-default-url: true
#
#springdoc.api-docs.enabled=true
#springdoc.api-docs.path=/api-docs/json
#
#springdoc.swagger-ui.path=/api-docs/ # <==== mind the trailing slash
#springdoc.swagger-ui.disable-swagger-default-url=true