logging:
  level:
    root: INFO
  pattern:
    level: "%clr([%X{X-B3-TraceId}]){blue} %clr(%5p){green}"

ramsey:
  work-unit:
    page-size:
      default: 5
      max: 500

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: ${JDBC_BATCH_SIZE:500}
        order_inserts: true
        order_updates: true

server:
  forward-headers-strategy: framework # Needed for api docs behind reverse proxy
