logging:
  level:
    root: INFO
  pattern:
    level: "%clr([%X{X-B3-TraceId}]){blue} %clr(%5p){green}"

ramsey:
  work-unit:
    page-size:
      default: 5
      max: 500

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 500