spring:
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update} # Creates tables [none, create, update]
    defer-datasource-initialization: true
  sql:
    init:
      mode: ${SQL_INIT_MODE:never} # Runs data.sql for inserts [never, always]
  datasource:
    url: jdbc:mysql://127.0.0.1:36001/ramsey-dev?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useLocalSessionState=true&cacheServerConfiguration=true&maintainTimeStats=false&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true
    username: ${DB_USER}
    password: ${DB_PASS}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 36000

