version: '3.9'

services:

  ramsey-mw:
    image: benferenchak/ramsey-mw:dev
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - 4040:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_USER: ramsey-user-dev
      DB_PASS: <password>
    logging:
      driver: json-file
      options:
        max-size: "10m"

  ramsey-queue-manager:
    image: benferenchak/ramsey-queue-manager:dev
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      SPRING_PROFILES_ACTIVE: dev
      WORK_UNIT_ANALYSIS_TYPE: TARGETED
      WORK_UNIT_QUEUE_DEPTH_MIN: 50000
      WORK_UNIT_QUEUE_DEPTH_MAX: 100000
      WORK_UNIT_ASSIGNMENT_COUNT: 2000
    depends_on:
      - ramsey-mw
    logging:
      driver: json-file
      options:
        max-size: "10m"

  ramsey-worker:
    image: benferenchak/ramsey-worker:dev
    deploy:
      resources:
        limits:
          cpus: '1.20'
          memory: '768M'
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      SPRING_PROFILES_ACTIVE: dev
      WORK_UNIT_FETCH_COUNT: 500
      WORK_UNIT_PUBLISH_COUNT: 200
    depends_on:
      - ramsey-mw
    logging:
      driver: json-file
      options:
        max-size: "10m"
