services:

  redis:
    image: redis:8.4-alpine
    networks:
      - ramsey-net
    ports:
      - "6379:6379"
    mem_limit: 8g

  ramsey-mw:
    image: benferenchak/ramsey-mw:stage-progression
    networks:
      - ramsey-net
    ports:
      - "4040:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_USER: ramsey-user-dev
      DB_PASS: ${MYSQL_PASSWORD}
      JDBC_BATCH_SIZE: 5000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOGGING_LEVEL_ROOT: INFO
    depends_on:
      - redis
    logging:
      driver: json-file
      options:
        max-size: "10m"
    restart: on-failure
    mem_limit: 2g

  ramsey-queue-manager:
    image: benferenchak/ramsey-queue-manager:stage-progression
    networks:
      - ramsey-net
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORK_UNIT_ANALYSIS_TYPE: TARGETED
      WORK_UNIT_QUEUE_DEPTH_MIN: 4000000
      WORK_UNIT_QUEUE_DEPTH_MAX: 8000000
      LOGGING_LEVEL_ROOT: INFO
    depends_on:
      - ramsey-mw
      - redis
    logging:
      driver: json-file
      options:
        max-size: "10m"
    restart: on-failure
    mem_limit: 2g

  ramsey-worker:
    image: benferenchak/ramsey-worker:develop
    networks:
      - ramsey-net
    environment:
      SPRING_PROFILES_ACTIVE: dev
      WORK_UNIT_FETCH_COUNT: 50000
      WORK_UNIT_PUBLISH_COUNT: 50000
      WORK_UNIT_ROUTER_FREQ: 10000
      LOGGING_LEVEL_ROOT: WARN
      MW_HOST: http://ramsey-mw:8080
    depends_on:
      ramsey-mw:
        condition: service_healthy
      redis:
        condition: service_started
    logging:
      driver: json-file
      options:
        max-size: "10m"
    restart: on-failure
    mem_limit: 2g

  ramsey-worker-rust:
    image: benferenchak/ramsey-worker-rust:stage-progression
    networks:
      - ramsey-net
    environment:
      RAMSEY_API_URL: http://ramsey-mw:8080/api/ramsey
      RAMSEY_CAMPAIGN_ID: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WORK_UNIT_FETCH_COUNT: 50000
      WORK_UNIT_PUBLISH_COUNT: 10000
      CLIENT_PHONE_HOME_FREQ: 60000
      PUBLISH_RESULTS: "false"
    depends_on:
      ramsey-mw:
        condition: service_healthy
      redis:
        condition: service_started
    logging:
      driver: json-file
      options:
        max-size: "10m"
    restart: on-failure
    mem_limit: 2g

  # ramsey-ui:
  #   image: benferenchak/ramsey-ui:develop
  #   networks:
  #     - ramsey-net
  #   ports:
  #     - "8501:8501"
  #   environment:
  #     API_BASE_URL: http://ramsey-mw:8080
  #     STAGE_ID: 3
  #   depends_on:
  #     - ramsey-mw
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #   restart: on-failure

networks:
  ramsey-net:
    external: true