services:
  ramsey-mw:
    image: benferenchak/ramsey-mw:develop
    networks:
      - ramsey-net
    ports:
      - "4040:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_USER: ramsey-user-dev
      DB_PASS: <password>
      JAVA_OPTS: -XX:UseSVE=0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    restart: on-failure
  ramsey-queue-manager:
    image: benferenchak/ramsey-queue-manager:develop
    networks:
      - ramsey-net
    environment:
      SPRING_PROFILES_ACTIVE: dev
      WORK_UNIT_ANALYSIS_TYPE: TARGETED
      WORK_UNIT_QUEUE_DEPTH_MIN: 50000
      WORK_UNIT_QUEUE_DEPTH_MAX: 100000
      WORK_UNIT_ASSIGNMENT_COUNT: 2000
      JAVA_OPTS: -XX:UseSVE=0
    depends_on:
      - ramsey-mw
    logging:
      driver: json-file
      options:
        max-size: "10m"
    restart: on-failure
  ramsey-worker:
    image: benferenchak/ramsey-worker:develop
    networks:
      - ramsey-net
    environment:
      SPRING_PROFILES_ACTIVE: dev
      WORK_UNIT_FETCH_COUNT: 500
      WORK_UNIT_PUBLISH_COUNT: 200
      JAVA_OPTS: -XX:UseSVE=0
    depends_on:
      - ramsey-mw
    logging:
      driver: json-file
      options:
        max-size: "10m"
    restart: on-failure

  ramsey-ui:
    image: benferenchak/ramsey-ui:develop
    networks:
      - ramsey-net
    ports:
      - "8501:8501"
    environment:
      API_BASE_URL: http://ramsey-mw:8080
    depends_on:
      - ramsey-mw
    logging:
      driver: json-file
      options:
        max-size: "10m"
    restart: on-failure

networks:
  ramsey-net:
    external: true