services:
  db:
    image: mysql:latest
    container_name: ramsey-db-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: <password>
    volumes:
      - /Users/benjaminferenchak/IdeaProjects/ramsey/ramsey-mw/database/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
    restart: on-failure
